services:
  nginx-php:
    image: wyveo/nginx-php-fpm:php74
    restart: always
    ports:
      - ${PORT}:8432
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - synergy

networks:
  synergy:
    driver: bridge
